#!/bin/bash
set -e

# Jerry-03: Email Recovery - Simulation Script
# This script simulates Jerry's original infrastructure creation
# It creates AWS resources that match the provided state file backup

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EXERCISE_DIR="$(dirname "$SCRIPT_DIR")"
SETUP_DIR="$EXERCISE_DIR/setup"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║   Jerry-03: Email Recovery - Simulation                   ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""

echo -e "${YELLOW}Scenario:${NC}"
echo "Jerry was working on Terraform from his laptop with LOCAL state."
echo "His laptop's hard drive died. Fortunately, he emailed himself"
echo "a backup of terraform.tfstate last week."
echo ""
echo -e "${YELLOW}This script will:${NC}"
echo "1. Generate a unique bucket name"
echo "2. Create the AWS infrastructure Jerry originally built"
echo "3. Update jerry-backup.tfstate with the actual resource IDs"
echo "4. Update the Terraform configuration to match"
echo ""
echo -e "${YELLOW}After this runs:${NC}"
echo "- AWS resources will exist (Jerry's infrastructure)"
echo "- jerry-backup.tfstate will have the correct resource IDs"
echo "- BUT you won't have a local state file (simulating the disaster)"
echo ""

# Check prerequisites
if ! command -v aws &> /dev/null; then
    echo -e "${RED}Error: AWS CLI is not installed${NC}"
    exit 1
fi

if ! command -v jq &> /dev/null; then
    echo -e "${RED}Error: jq is not installed${NC}"
    exit 1
fi

# Check AWS credentials
if ! aws sts get-caller-identity &> /dev/null; then
    echo -e "${RED}Error: AWS credentials not configured${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Prerequisites check passed${NC}"
echo ""

# Generate unique bucket name
RANDOM_SUFFIX=$(openssl rand -hex 4)
BUCKET_NAME="jerry-important-data-${RANDOM_SUFFIX}"
AWS_REGION="us-east-1"

echo -e "${BLUE}Step 1: Generating unique bucket name${NC}"
echo "Bucket name: ${BUCKET_NAME}"
echo ""

# Create S3 bucket (simulating what Jerry originally created)
echo -e "${BLUE}Step 2: Creating S3 bucket (Jerry's original infrastructure)${NC}"

if aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
    echo -e "${YELLOW}⚠ Bucket already exists, skipping creation${NC}"
else
    aws s3api create-bucket \
        --bucket "$BUCKET_NAME" \
        --region "$AWS_REGION" \
        --create-bucket-configuration LocationConstraint="$AWS_REGION" 2>/dev/null || \
    aws s3api create-bucket \
        --bucket "$BUCKET_NAME" \
        --region "$AWS_REGION"

    echo -e "${GREEN}✓ Bucket created: ${BUCKET_NAME}${NC}"
fi

# Add tags to the bucket
echo -e "${BLUE}Step 3: Adding tags to bucket${NC}"
aws s3api put-bucket-tagging \
    --bucket "$BUCKET_NAME" \
    --tagging "TagSet=[
        {Key=Name,Value=\"Jerry Important Data\"},
        {Key=Owner,Value=jerry},
        {Key=Environment,Value=production},
        {Key=Exercise,Value=jerry-03-email-recovery},
        {Key=Track,Value=jerry},
        {Key=Category,Value=state},
        {Key=ManagedBy,Value=terraform}
    ]"
echo -e "${GREEN}✓ Tags added${NC}"

# Enable versioning on the bucket
echo -e "${BLUE}Step 4: Enabling versioning${NC}"
aws s3api put-bucket-versioning \
    --bucket "$BUCKET_NAME" \
    --versioning-configuration Status=Enabled
echo -e "${GREEN}✓ Versioning enabled${NC}"
echo ""

# Update jerry-backup.tfstate with the actual bucket name
echo -e "${BLUE}Step 5: Updating jerry-backup.tfstate with actual resource IDs${NC}"
STATE_FILE="$EXERCISE_DIR/jerry-backup.tfstate"

if [ ! -f "$STATE_FILE" ]; then
    echo -e "${RED}Error: jerry-backup.tfstate not found${NC}"
    exit 1
fi

# Replace BUCKET_NAME_PLACEHOLDER with actual bucket name
sed -i.bak "s/BUCKET_NAME_PLACEHOLDER/$BUCKET_NAME/g" "$STATE_FILE"
rm -f "${STATE_FILE}.bak"

echo -e "${GREEN}✓ State file updated with bucket name: ${BUCKET_NAME}${NC}"

# Update setup/variables.tf with the bucket name
echo -e "${BLUE}Step 6: Updating Terraform configuration${NC}"

# Create terraform.tfvars with the bucket name
cat > "$SETUP_DIR/terraform.tfvars" << EOF
# Auto-generated by simulate-jerry.sh
# This file sets the bucket name to match Jerry's infrastructure

bucket_name = "$BUCKET_NAME"
aws_region  = "$AWS_REGION"
EOF

echo -e "${GREEN}✓ Created terraform.tfvars with bucket name${NC}"
echo ""

# Verify resources exist
echo -e "${BLUE}Step 7: Verifying AWS resources${NC}"

if aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
    echo -e "${GREEN}✓ Bucket exists in AWS${NC}"
else
    echo -e "${RED}✗ Bucket verification failed${NC}"
    exit 1
fi

VERSIONING_STATUS=$(aws s3api get-bucket-versioning --bucket "$BUCKET_NAME" --query 'Status' --output text)
if [ "$VERSIONING_STATUS" == "Enabled" ]; then
    echo -e "${GREEN}✓ Versioning is enabled${NC}"
else
    echo -e "${RED}✗ Versioning verification failed${NC}"
    exit 1
fi

echo ""
echo -e "${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║   Simulation Complete!                                     ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${YELLOW}What just happened:${NC}"
echo "✓ Created S3 bucket: ${BUCKET_NAME}"
echo "✓ Enabled versioning on the bucket"
echo "✓ Updated jerry-backup.tfstate with real resource IDs"
echo "✓ Created terraform.tfvars with bucket configuration"
echo ""
echo -e "${YELLOW}The Disaster Scenario:${NC}"
echo "- AWS infrastructure exists (you can see it in the console)"
echo "- jerry-backup.tfstate has the correct resource mappings"
echo "- BUT there's no terraform.tfstate in setup/ (Jerry's laptop died!)"
echo ""
echo -e "${YELLOW}Your Mission:${NC}"
echo "1. cd setup/"
echo "2. Try: terraform init && terraform plan"
echo "   (Notice: Terraform doesn't know about the existing infrastructure!)"
echo "3. Examine: cat ../jerry-backup.tfstate | jq ."
echo "   (This is Jerry's emailed backup - understand its structure)"
echo "4. Recover the state using one of these methods:"
echo "   - Method A: terraform state push ../jerry-backup.tfstate"
echo "   - Method B: Push state, then migrate to S3 backend"
echo "   - Method C: Use terraform import to rebuild state"
echo "5. Verify: terraform plan (should show 'No changes')"
echo ""
echo -e "${BLUE}Hint:${NC} The state file is Terraform's memory. Without it,"
echo "      Terraform doesn't know what infrastructure it manages!"
echo ""
echo -e "${YELLOW}To reset and try again:${NC}"
echo "  ../.validator/reset.sh"
echo ""
